### ISSUE TITLE
Instantiating Elements

### ISSUE THREAD

**Issue by Pharylon** [Pabreetzio/AngryElectron#1]
I have a question about how I'm supposed to instantiate Elements. When the Parser finds the text string "Na," where does it look up information on Sodium's name, atomic weight, etc so it can feed that into the Element's constructor? Is that what the TableOfElements class is for? If so, how do I properly use it?

**Comment by Pabreetzio** [comment]
Look up the flyweight design pattern, I believe that's what elements will be designed as. Then consider that instead of constructing elements you'll be using ones that already exist. Yes the table of elements might be where they exist. However later I might decide to use a different collection of elements. So maybe you don't get your elements from table of elements but just any ICollection<Element>. Table of elements was never finished really as I recall.

**Comment by Pharylon** [comment]
Just looked it up. :)  If I'm understanding the intent correctly, we'll have an ICollection<Element> that contains an instance of every element (right now, that is TableOfElements, reading from the json file), and the Parser will just need to create references to those elements in the chemical equation. Right?
